// Service-Worker: offline spielbar, Cache-Busting über Inhalts-Hash (tools/update_sw.py)
const VERSION = 'b28b09e1b2';
const CACHE = 'stuntbahn-' + VERSION;
const ASSETS = [
  './',
  'assets/car/goblin.glb',
  'assets/car/goblin_far.glb',
  'assets/car/goblin_lod.glb',
  'assets/car/goblin_mid.glb',
  'assets/deco/rocks.glb',
  'assets/hdr/sky_512.hdr',
  'assets/sammlung.bin',
  'assets/sammlung.json',
  'assets/sky/sky.jpg',
  'assets/sky/sky.json',
  'assets/snd/sfx.json',
  'assets/snd/sfx.m4a',
  'assets/tex/asphalt_arm.ktx2',
  'assets/tex/asphalt_detail_nor.webp',
  'assets/tex/asphalt_diff.ktx2',
  'assets/tex/asphalt_nor.ktx2',
  'assets/tex/concrete_arm.ktx2',
  'assets/tex/concrete_diff.ktx2',
  'assets/tex/concrete_nor.ktx2',
  'assets/tex/fir_card_0.webp',
  'assets/tex/fir_card_1.webp',
  'assets/tex/grass_arm.ktx2',
  'assets/tex/grass_diff.ktx2',
  'assets/tex/grass_nor.ktx2',
  'assets/tex/gravel_diff.webp',
  'assets/tex/gravel_nor.webp',
  'assets/tex/imp/impostor.json',
  'assets/tex/imp/tanne0_farbe.webp',
  'assets/tex/imp/tanne0_nor.webp',
  'assets/tex/imp/tanne1_farbe.webp',
  'assets/tex/imp/tanne1_nor.webp',
  'assets/tex/metal_arm.ktx2',
  'assets/tex/metal_diff.ktx2',
  'assets/tex/metal_nor.ktx2',
  'assets/tex/pad_arm.ktx2',
  'assets/tex/pad_diff.ktx2',
  'assets/tex/pad_nor.ktx2',
  'assets/tex/veg_atlas.json',
  'assets/tex/veg_atlas.webp',
  'css/style.css',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'index.html',
  'lib/addons/libs/basis/basis_transcoder.js',
  'lib/addons/libs/basis/basis_transcoder.wasm',
  'lib/addons/libs/ktx-parse.module.js',
  'lib/addons/libs/meshopt_decoder.module.js',
  'lib/addons/libs/zstddec.module.js',
  'lib/addons/loaders/GLTFLoader.js',
  'lib/addons/loaders/HDRLoader.js',
  'lib/addons/loaders/KTX2Loader.js',
  'lib/addons/math/ColorSpaces.js',
  'lib/addons/utils/BufferGeometryUtils.js',
  'lib/addons/utils/SkeletonUtils.js',
  'lib/addons/utils/WorkerPool.js',
  'lib/three.core.min.js',
  'lib/three.module.min.js',
  'manifest.webmanifest',
  'src/ai/autopilot.js',
  'src/ai/drift.js',
  'src/ai/ideal.js',
  'src/ai/profile.js',
  'src/audio/sound.js',
  'src/build.js',
  'src/core/gforce.js',
  'src/core/showspeed.js',
  'src/core/util.js',
  'src/game/cinecam.js',
  'src/game/ghost.js',
  'src/game/highlights.js',
  'src/game/input.js',
  'src/game/jumpassist.js',
  'src/game/race.js',
  'src/game/replay.js',
  'src/game/sammlung.js',
  'src/game/store.js',
  'src/game/trklib.js',
  'src/game/warn.js',
  'src/game/zielshow.js',
  'src/gfx/camera.js',
  'src/gfx/carlod.js',
  'src/gfx/carmesh.js',
  'src/gfx/cockpit.js',
  'src/gfx/cockpitmat.js',
  'src/gfx/deco.js',
  'src/gfx/deko.js',
  'src/gfx/env.js',
  'src/gfx/fx.js',
  'src/gfx/gauges.js',
  'src/gfx/jumpdeck.js',
  'src/gfx/kern/autopilot.js',
  'src/gfx/kern/impostor.js',
  'src/gfx/kern/oktaeder.js',
  'src/gfx/kern/reflex.js',
  'src/gfx/kern/startprobe.js',
  'src/gfx/kern/taau.js',
  'src/gfx/kern/taau_mathe.js',
  'src/gfx/kinolook.js',
  'src/gfx/kulisse.js',
  'src/gfx/kulisse2.js',
  'src/gfx/lineviz.js',
  'src/gfx/materials.js',
  'src/gfx/post.js',
  'src/gfx/pyro.js',
  'src/gfx/quality.js',
  'src/gfx/scheibe.js',
  'src/gfx/themes.js',
  'src/gfx/wetter.js',
  'src/gfx/world.js',
  'src/gfx/zeit.js',
  'src/main.js',
  'src/physics/air.js',
  'src/physics/car.js',
  'src/physics/collide.js',
  'src/physics/extras.js',
  'src/track/build.js',
  'src/track/deco.js',
  'src/track/defs.js',
  'src/track/gelaende.js',
  'src/track/generator.js',
  'src/track/generator3d.js',
  'src/track/generatorG.js',
  'src/track/kulisse.js',
  'src/track/kulisse2.js',
  'src/track/obstacles.js',
  'src/track/pieces.js',
  'src/track/pieces_3d.js',
  'src/track/pieces_gel.js',
  'src/track/pieces_trk.js',
  'src/track/scenery.js',
  'src/track/showcase.js',
  'src/track/terrgrid.js',
  'src/track/themes.js',
  'src/track/trk.js',
  'src/track/trkdesign.js',
  'src/track/trkelems.js',
  'src/track/trkgen.js',
  'src/track/trkimport.js',
  'src/track/trkterrain.js',
  'src/track/vao.js',
  'src/track/verify.js',
  'src/track/wetter.js',
  'src/track/zeit.js',
  'src/ui/cliprec.js',
  'src/ui/gmeter.js',
  'src/ui/minimap.js',
  'src/ui/ui.js'
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('stuntbahn-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('index.html', { cacheName: CACHE }).then((r) => r || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((r) => r || fetch(req).then((res) => {
    if (res.ok) { const cp = res.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); }
    return res;
  })));
});
